sudo: false
language: ruby
rvm: 2.3.8
bundler_args: --without development
env:
  - OPENCOURTS_DATABASE_USER=postgres

before_install:
  - gem install bundler

  # Elastic
  - curl -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.2.tar.gz
  - tar xzf elasticsearch-1.7.2.tar.gz
  - "echo \"script.engine.groovy.inline.aggs: on\" >> elasticsearch-1.7.2/config/elasticsearch.yml"
  - elasticsearch-1.7.2/bin/elasticsearch -d

before_script:
  - psql -c 'create database opencourts_test;' -U postgres
  - "cp config/configuration.yml.travis config/configuration.yml"
  - bundle exec rake db:schema:load

script:
  - bundle exec rspec spec

addons:
  postgresql: '9.4'
