FORMAT: 1A
HOST: http://otvorenesudy.sk

# Otvorené Súdy API

Otvorené Súdy Public data project aimed at creating much more user friendly interface to 
interesting public data provided by [Departement of Justice](http://justice.gov.sk) and [The Judical Council of Slovak Republic](http://sudnarada.gov.sk).

**Note**: Currently, we only provide API for Decrees.

## Allowed HTTP Requests:

* `GET` - To Get a Resource or List of Resource.

## Requirements

* API key - In order to use our API, we require that you
obtain an API key. API key is a part of every URL as a parameter. 

    Example: `/api/decrees?api_key=YOUR_API_KEY`

**Note**: All requests are prefixed with `/api` path, e.g. `/decrees` is actually `/api/decrees`.

# Decrees API
Decrees issued on specific court by one or more judges.

## Decrees Collection [/decrees]

Decree has following attributes:

- **id** - id of a decree
- **case_number** - case number of decree (*spisová značka* in Slovak)
- **file_number** - file number of decree (*identifikačné číslo spisu* in Slovak)
- **ecli** - European Case Law Identifier
- **text** - text of decree extracted from pdf document
- **date** - date when decree was issued\
- **pages_urls** - urls to pages as images extracted from decree pdf
- **uri** - uri to original decree published at [Departement of Justice](http://justice.gov.sk) website.
- **document_url** - url to original pdf document
- **court** - court where the decree was issued
  - **id** - id of court
  - **name** - name of the court
  - **address** - address of the court
- **form** - form of the decree
  - **code** - code of the form
  - **value** - value of the form
- **legislation_area** - legislation area of the decree
  - **value** - name of the legislation area
- **legislation_subarea** - legislation area of the decree
  - **value** - name of the legislation subarea
- **natures** - natures of the decree (*povaha rozhodnutia* in Slovak)
  - **value** - name of the nature
- **judges** - 
  - **id** - id of the judge
  - **name** - name od the judge
- **legislations** - legislations mentioned in the decre
  - **name** - name of the legislation
  - **number**
  - **letter**
  - **paragraph**
  - **section**
  - **type**
  - **value** - legislation full value
  - **value_unprocessed** - unprocessed value of legislation
- **defendants** - defendants mentioned in hearings
  - **name**
- **opponents** - opponents mentioned in hearings
  - **name**
- **proposers** - proposers mentioned in hearing
  - **name**
- **updated_at** - date when decree was created in our database 
- **created_at** - date when decree was updated in our database 

### List all Notes [GET]
+ Response 200

    + Headers
    
            Content-Type: application/json
            Link: "/api/decrees?page=1; rel='next'"
    + Body
    
            {
                "decrees":[
                    {
                        "id": 1208954,
                        "case_number": "11Rob/106/2014",
                        "file_number": "8314209921",
                        "ecli": "ECLI:SK:OSHE:2014:8314209921.1",
                        "text": "Súd: Spisová značka: ...",
                        "date": "2014-10-06",
                        "pages_urls": [
                            "http://otvorenesudy.sk/decrees/1208954/pages/1/image"
                        ],
                        "uri": "http://www.justice.gov.sk/Stranky/Sudne-rozhodnutia/Sudne-rozhodnutie-detail.aspx?PorCis=7DDB0A36-7144-4D1F-A8B6-AD7C952DBD91&PojCislo=330109",
                        "document_url": "http://otvorenesudy.sk/decrees/1208954/document",
                        "created_at": "2014-11-09T14:35:24+01:00",
                        "updated_at": "2014-11-09T14:35:27+01:00",
                        "court": {
                            "id": 23,
                            "name": "Okresný súd Humenné"
                        },
                        "form": {
                            "code": "N",
                            "value": "Uznesenie"
                        },
                        "legislation_area": {
                            "value": "Trestné právo"
                        },
                        "legislation_subarea": {
                            "value": "Majetok"
                        },
                        "natures": [
                            { 
                                "value": "Prvostupňové nenapadnuté opravnými prostriedkami"
                            }
                        ],
                        "judges": [
                            {
                                "id": 1676,
                                "name": "Mgr. Zdenka Škubalová"
                            }
                        ],
                        "legislations": [
                            {
                                "name": "o súdnych poplatkoch",
                                "number": 71,
                                "letter": null,
                                "paragraph": "10",
                                "section": "1",
                                "type": "Zákon č.",
                                "year": 1992,
                                "value": "Zákon č. 71/1992 o súdnych poplatkoch, § 10, Odsek 1",
                                "value_unprocessed": "Zákon č. 71/1992 o súdnych poplatkoch,§ 10, Odsek 1",
                                "external_url": "http://www.zakonypreludi.sk/zz/1992-71#p10-1"
                            }
                        ],
                        "defendants": [],
                        "opponents": [],
                        "proposers": []
                    }
                ]
            }
            