require 'active_support/inflector'
require 'active_support/multibyte'

require 'ruby/string'

require 'docsplit'
require 'mechanize'
require 'murmurhash3'
require 'nokogiri'
require 'settingslogic'

require 'core/configuration'
require 'core/output'
require 'core/identify'
require 'core/pluralize'
require 'core/storage'
require 'core/storage/cache'
require 'core/storage/utils'
require 'core/text_extractor'
require 'core/request'
require 'core/request/list'
require 'core/downloader'
require 'core/agent'
require 'core/factory'
require 'core/factory/supplier'
require 'core/factories'
require 'core/parser'
require 'core/parser/html'
require 'core/persistor'
require 'core/crawler'
require 'core/crawler/list'
require 'core/version'

module Core
end
